; Needed for "supervisorctl" command to work
[unix_http_server]
file=/srv/app/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)

[supervisord]
pidfile=/srv/app/supervisord.pid
logfile=/var/log/supervisor/supervisord.log
childlogdir=/var/log/supervisor            ; ('AUTO' child log dir, default $TEMP)
logfile_maxbytes=50MB
logfile_backups=10
loglevel=debug
nodaemon=false
minfds=1024
minprocs=200

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///srv/app/supervisor.sock ; use a unix:// URL  for a unix socket

[program:ckan_gather_consumer]
command=/usr/local/bin/ckan --config=/srv/app/ckan.ini harvester gather-consumer
numprocs=1
stdout_logfile=/var/log/ckan/std/gather_consumer.log
stderr_logfile=/var/log/ckan/std/gather_consumer.log
autostart=true
autorestart=true
startsecs=10

[program:ckan_fetch_consumer]
command=/usr/local/bin/ckan --config=/srv/app/ckan.ini harvester fetch-consumer
numprocs=1
stdout_logfile=/var/log/ckan/std/fetch_consumer.log
stderr_logfile=/var/log/ckan/std/fetch_consumer.log
autostart=true
autorestart=true
startsecs=10

[program:cron]
command=/usr/sbin/cron -f
numprocs=1
stdout_logfile=/var/log/ckan/std/cron.log
stderr_logfile=/var/log/ckan/std/cron.log
autostart=true
autorestart=true
startsecs=10

