FROM ckan/ckan-dev:2.11.4


# Workaround from https://github.com/ckan/ckan-docker/issues/196
USER root
RUN mkdir /srv/app/.local && chown ckan /srv/app/.local
RUN mkdir /srv/app/.cache && chown ckan /srv/app/.cache

# Copy harvester scripts
COPY config/*.sh  /srv/app

RUN chown -R ckan:ckan-sys ${APP_DIR} && chmod 755 /srv/app/*.sh

# Make WAF folder writeable by ckan user
RUN mkdir -p /var/www/html && chown -R ckan:ckan-sys /var/www/html


USER ckan

# Install any extensions needed by your CKAN instance
# See Dockerfile.dev for more details and examples



# Copy custom initialization scripts
COPY --chown=ckan-sys:ckan-sys docker-entrypoint.d/* /docker-entrypoint.d/

# Apply any patches needed to CKAN core or any of the built extensions (not the
# runtime mounted ones)
COPY --chown=ckan-sys:ckan-sys patches ${APP_DIR}/patches

# Make the WAF folder owned by ckan
USER root
RUN mkdir -p /var/www/html && chown ckan /var/www/html


USER ckan

RUN for d in $APP_DIR/patches/*; do \
        if [ -d $d ]; then \
            for f in `ls $d/*.patch | sort -g`; do \
                cd $SRC_DIR/`basename "$d"` && echo "$0: Applying patch $f to $SRC_DIR/`basename $d`"; patch -p1 < "$f" ; \
            done ; \
        fi ; \
    done

