# SPDX-FileCopyrightText: 2024 PNED G.I.E.
#
# SPDX-License-Identifier: AGPL-3.0-only

GET http://localhost:5500/api/action/package_search?facet.field=["organization","theme","access_rights","res_format"]&facet.limit=10&rows=0
