apiVersion: batch/v1
kind: CronJob
metadata:
  name: run-harvester
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 502
            runAsGroup: 503
          containers:
          - name: ckan
            image: "{{ .Values.webapp.image_ckan }}:{{ .Values.webapp.tag }}"
            command: ["/srv/app/run_harvester.sh"]
            volumeMounts:
              - mountPath: /srv/app
                name: home-dir
                readOnly: true
              - mountPath: /var/www/html
                name: waf-dir
                readOnly: false
          volumes:
            - name: home-dir
              persistentVolumeClaim:
                claimName: home-dir
            - name: waf-dir
              persistentVolumeClaim:
                claimName: waf-dir