apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrets-webapp
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: sage-ro
    kind: SecretStore
  target:
    name: secrets-webapp
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: CKAN_SYSADMIN_NAME
      remoteRef:
        key: sage/sage-ckan/ckan_admin
        property: CKAN_ADMIN_USERNAME
    - secretKey: CKAN_SYSADMIN_PASSWORD
      remoteRef:
        key: sage/sage-ckan/ckan_admin
        property: CKAN_ADMIN_PASSWORD
    - secretKey: CKAN_SYSADMIN_EMAIL
      remoteRef:
        key: sage/sage-ckan/ckan_admin
        property: CKAN_ADMIN_EMAIL