apiVersion: apps/v1
kind: Deployment
metadata:
  name: datapusher
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ckan
      app.kubernetes.io/component: datapusher
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ckan
        app.kubernetes.io/component: datapusher
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: datapusher
          image: docker.io/ckan/ckan-base-datapusher:0.0.21
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 92
          ports:
            - name: http
              containerPort: 8800
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
