apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - services.yaml
  - postgresql.yaml
  - solr.yaml
  - redis.yaml
  - datapusher.yaml
  - storage.yaml
  - initialize-job.yaml
  - reindex-job.yaml
  - ckan.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: ckan
