webapp:
  name: ckandev
  group: ckandev
  path: "/"
  tls:
    fqdn: ckandev.data-commons.k8s.ucar.edu
    DNSAlias: ckandev.ucar.edu
    secretName: incommon-cert-sage-ckandev
  container:
    image: nginx
    port: 443
  images:
    solr: ghcr.io/ncar/sage-dashsearch-solr
    postgres: ghcr.io/ncar/sage-dashsearch-postgres
    nginx: ghcr.io/ncar/sage-dashsearch-nginx
    ckan: ghcr.io/ncar/sage-dashsearch-ckan
  tag: 2025-10-29.20.27

